#!/bin/sh
# call rsync to mirror new releases from ftp.hostserver.de

set -eu

if [ $# != 0 ]
then
	echo usage: rsync-releases >&2
	exit 2
fi

# it does not make sense to download old releases again
excludeversions=`jot - 20 60 1`

host="${host:=217.31.80.35}"
bwlimit="${bwlimit:=1000}"
debug="${debug:=debug}"
rsyncoptions="--delete --exclude .~tmp~ --exclude snapshots"
rsync="/usr/local/bin/rsync --bwlimit=$bwlimit $rsyncoptions"
tag="rsync-releases[$$]"

logger -p daemon.info -t "$tag" "openbsd start"
for version in $excludeversions
do
	release="${version%[0-9]}.${version##[0-9]}"
	rsyncoptions="$rsyncoptions --exclude $release"
done
rsyncoptions="$rsyncoptions --exclude unsupported"
rsync="/usr/local/bin/rsync --bwlimit=$bwlimit $rsyncoptions"

# get everything that is not a snapshot or an old release

url="rsync://$host/OpenBSD/"
dir="/data/mirror/openbsd/ftp"
$rsync -av "$url" "$dir" | logger -p "daemon.$debug" -t rsync
logger -p daemon.notice -t "$tag" "openbsd success"
exit 0
