#!/bin/sh
# call rsync to mirror snapshot for one arch from ftp.hostserver.de

set -eu

if [ $# != 1 ]
then
	echo usage: rsync-snapshot-arch arch >&2
	exit 2
fi
arch="$1"

host=217.31.80.35
bwlimit=3000
rsyncoptions="--partial --delete-excluded --exclude '.~tmp~'"
rsync="/usr/local/bin/rsync --bwlimit=$bwlimit $rsyncoptions"
tag="rsync-snapshot-arch[$$]"

# create a new directory with the old files hardlinked
# if the new directory is already there, use this partial download

logger -p daemon.info -t "$tag" "openbsd $arch start"
url="rsync://$host/OpenBSD/snapshots/$arch/"
dir="/data/mirror/openbsd/ftp/snapshots/$arch"
if ! [ -d "$dir.new" ]
then
	mkdir -- "$dir.new" && ln -- "$dir"/* "$dir.new"
fi
$rsync -av "$url" "$dir.new" | logger -p daemon.debug -t rsync

# extract the signify key version from the base.tgz name

base="`echo "$dir.new"/base??.tgz`"
if ! [ -f "$base" ]
then
	echo no base tgz in "$dir.new" >&2
	exit 1
fi
version="${base##*/base}"
version="${version%.tgz}"
key="/etc/signify/openbsd-$version-base.pub"
logger -p daemon.info -t "$tag" "openbsd $arch signify key $key"

# verify the signature of the new downloaded files

if ! ( cd "$dir.new" && signify -C -p "$key" -x SHA256.sig )
then
	logger -p daemon.warning -t "$tag" "openbsd $dir fail"
	exit 1
fi | logger -p daemon.debug -t signify

# replace the old files with the verfied new ones

mv -- "$dir" "$dir.old"
mv -- "$dir.new" "$dir"
rm -rf -- "$dir.old"
logger -p daemon.notice -t "$tag" "openbsd $arch success"
exit 0
